spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    database: default
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: sa
    driver-class-name: org.h2.Driver
    generate-unique-name: 'false'
    username: sa
    url: jdbc:h2:mem:mydb
    continue-on-error: 'false'
    initialize: 'false'
  h2:
    console:
        enabled: 'true'